In [2]:
import numpy as np

The Basics

In [3]:
'''
What is an array in python?

In Python, an array is a collection of elements of the same data type, stored in contiguous memory locations. 
An array can be of any data type such as integers, floating-point numbers, or strings. 
Arrays are used to store and manipulate a large number of elements efficiently.


What is contiguous memory locations?

Contiguous memory locations refer to a block of memory that is allocated for storing data, where all the memory addresses are consecutive or adjacent to each other. 
In other words, the memory addresses are in a sequence with no gaps between them.
When data is stored in contiguous memory locations, it allows for fast access and manipulation of data because the processor can access the data directly 
For example, if we have an array of integers, and the array is stored in contiguous memory locations, we can access any element in the array by simply 
calculating its memory address based on the index of the element and the size of each integer in memory.without having to go through other memory locations.


What is the difference between an array and a list?

Data Types: In Python, a list can contain elements of different data types, such as integers, strings, and even other lists. On the other hand, an array is
designed to store elements of the same data type. This is because arrays are stored in contiguous memory locations, and all elements must be of the same size.

Memory Management: Arrays are more efficient in terms of memory management than lists, especially when dealing with large amounts of data. This is because arrays 
allocate a single block of memory for all elements, whereas lists allocate separate blocks of memory for each element.

Functionality: Lists offer more functionality than arrays. For example, lists have built-in methods for sorting, reversing, and appending elements, 
whereas arrays do not. Additionally, lists can be easily resized, whereas arrays have a fixed size once they are created.

Libraries: Python provides built-in support for lists, but arrays are implemented through the array module. 
Therefore, arrays may require additional code to use them in some situations.

'''
list = [1,2,3]
print(list)
a = np.array([1,2,3], dtype = 'int16')
a

[1, 2, 3]


array([1, 2, 3], dtype=int16)

In [4]:
b = np.array([[9.0, 8.0, 7.0], [4.0, 5.0, 6.0]])
b

array([[9., 8., 7.],
       [4., 5., 6.]])

In [5]:
# Get Number of dimensions
a.ndim
b.ndim

2

In [6]:
# Get Shape
a.shape
b.shape

(2, 3)

In [7]:
# Get Type
'''
The main difference between int16 and int32 is the size of the integer data they can store.
int16 (or short) can store integer values between -32,768 and 32,767. It uses 16 bits (or 2 bytes) of memory to represent each integer value.
On the other hand, int32 (or int) can store integer values between -2,147,483,648 and 2,147,483,647. It uses 32 bits (or 4 bytes) of memory to represent each 
integer value.
In other words, int32 can store much larger integer values than int16, but it requires more memory to do so. 
This means that if we need to store larger integers, we would choose int32 to ensure that we have enough memory to store the data.
'''
a.dtype

dtype('int16')

In [8]:
# Get Size
a.itemsize

2

In [9]:
# Get total size
a.nbytes

6

In [10]:
# What will the following code print?
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


In [11]:
a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20
print(a)

"""
Explanation:

A numpy array a is created with values [1, 2, 3, 4, 5].
The variable b is assigned to the same array as a, meaning both a and b refer to the same numpy array object in memory.
The third element of b (which is also the third element of a) is changed to 20.
The array a is printed, which shows the modified values of [1, 2, 20, 4, 5].
Therefore, changing the value of an element in b also changes the corresponding element in a because both 
variables refer to the same numpy array object in memory.
"""

[ 1  2 20  4  5]


'\nExplanation:\n\nA numpy array a is created with values [1, 2, 3, 4, 5].\nThe variable b is assigned to the same array as a, meaning both a and b refer to the same numpy array object in memory.\nThe third element of b (which is also the third element of a) is changed to 20.\nThe array a is printed, which shows the modified values of [1, 2, 20, 4, 5].\nTherefore, changing the value of an element in b also changes the corresponding element in a because both \nvariables refer to the same numpy array object in memory.\n'