In [35]:
import numpy as np

The Basics

In [36]:
'''
What is an array in python?

In Python, an array is a collection of elements of the same data type, stored in contiguous memory locations. 
An array can be of any data type such as integers, floating-point numbers, or strings. 
Arrays are used to store and manipulate a large number of elements efficiently.


What is contiguous memory locations?

Contiguous memory locations refer to a block of memory that is allocated for storing data, where all the memory addresses are consecutive or adjacent to each other. 
In other words, the memory addresses are in a sequence with no gaps between them.
When data is stored in contiguous memory locations, it allows for fast access and manipulation of data because the processor can access the data directly 
For example, if we have an array of integers, and the array is stored in contiguous memory locations, we can access any element in the array by simply 
calculating its memory address based on the index of the element and the size of each integer in memory.without having to go through other memory locations.


What is the difference between an array and a list?

Data Types: In Python, a list can contain elements of different data types, such as integers, strings, and even other lists. On the other hand, an array is
designed to store elements of the same data type. This is because arrays are stored in contiguous memory locations, and all elements must be of the same size.

Memory Management: Arrays are more efficient in terms of memory management than lists, especially when dealing with large amounts of data. This is because arrays 
allocate a single block of memory for all elements, whereas lists allocate separate blocks of memory for each element.

Functionality: Lists offer more functionality than arrays. For example, lists have built-in methods for sorting, reversing, and appending elements, 
whereas arrays do not. Additionally, lists can be easily resized, whereas arrays have a fixed size once they are created.

Libraries: Python provides built-in support for lists, but arrays are implemented through the array module. 
Therefore, arrays may require additional code to use them in some situations.

'''
list = [1,2,3]
print(list)
a = np.array([1,2,3], dtype = 'int16')
a

[1, 2, 3]


array([1, 2, 3], dtype=int16)

In [37]:
b = np.array([[9.0, 8.0, 7.0], [4.0, 5.0, 6.0]])
b

array([[9., 8., 7.],
       [4., 5., 6.]])

In [38]:
# Get Number of dimensions
a.ndim
b.ndim

2

In [39]:
# Get Shape
a.shape
b.shape

(2, 3)

In [40]:
# Get Type
'''
The main difference between int16 and int32 is the size of the integer data they can store.
int16 (or short) can store integer values between -32,768 and 32,767. It uses 16 bits (or 2 bytes) of memory to represent each integer value.
On the other hand, int32 (or int) can store integer values between -2,147,483,648 and 2,147,483,647. It uses 32 bits (or 4 bytes) of memory to represent each 
integer value.
In other words, int32 can store much larger integer values than int16, but it requires more memory to do so. 
This means that if we need to store larger integers, we would choose int32 to ensure that we have enough memory to store the data.
'''
a.dtype

dtype('int16')

In [41]:
# Get Size
a.itemsize

2

In [42]:
# Get total size
a.nbytes

6

In [43]:
# What will the following code print?
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


Accessing/Changing specific element, rows, columns etc.

In [87]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [45]:
# Get a specific element [r,c]
# For example if we want the 13 value
a[1,5]


13

In [46]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [47]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [48]:
# Get a little more fancy [startindexLstopindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [49]:
# Change 13 to 20
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [50]:
# Change the 6th column
a[:,5] = 10
a

array([[ 1,  2,  3,  4,  5, 10,  7],
       [ 8,  9, 10, 11, 12, 10, 14]])

In [63]:
# 3-D Example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [64]:
# Get specific element (Work outside in)
# Get 8
b[1,1,1]

8

In [65]:
# Replace (Needs to be same dimension)
print(b[:,1,:])
b[:,1,:] = [[1,2],[3,4]]
b

[[3 4]
 [7 8]]


array([[[1, 2],
        [1, 2]],

       [[5, 6],
        [3, 4]]])

Initializing Different Types of Arrays

In [81]:
# All 0s Matrix

'''
The below code creates a NumPy array of shape (2, 3) containing all zeros.

Here's how it works:

    # np.zeros is a NumPy function that creates an array of a given shape and type, filled with zeros.
    # The argument to np.zeros is a tuple (2, 3), specifying the shape of the array. In this case, the array will have 2 rows and 3 columns.
    # The resulting array will have a data type of float64 by default, but we can specify a different data type by passing the dtype argument to the np.zeros function.
'''
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [82]:
'''
The below code creates a 3-dimensional NumPy array of shape (2, 3, 2) containing all zeros.

Here's how it works:

np.zeros is a NumPy function that creates an array of a given shape and type, filled with zeros.
The argument to np.zeros is a tuple (2, 3, 2), specifying the shape of the array. In this case, the array will have 2 "layers", each with 3 rows and 2 columns.
The resulting array will have a data type of float64 by default, but we can specify a different data type by passing the dtype argument to the np.zeros function.
'''

np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [83]:
# All 1's matrix
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [85]:
# Any other number (shape, value)
np.full((2,2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [89]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [90]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.82649214, 0.39698883],
       [0.18143217, 0.21609357],
       [0.57637842, 0.40970817],
       [0.13027391, 0.63555317]])

In [91]:
# What will the following code print?
'''
The code creates a NumPy array a with shape (2, 5) containing the values from 1 to 10, and then uses the np.full_like function to create a 
new array with the same shape as a but filled with the value 100.

The np.full_like function creates a new array with the same shape and data type as the input array, but with all elements set to a specified value. 
In this case, the function call np.full_like(a, 100) creates a new array with the same shape as a, which is (2, 5), and fills it with the value 100.
'''

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [92]:
# The Identity Matrix
'''
What is it used for?

Matrix operations: The identity matrix is the neutral element of matrix multiplication. 
When a matrix is multiplied by the identity matrix, the result is the same as the original matrix. 
The identity matrix is also used to define the inverse of a matrix.

Linear transformations: In linear algebra, the identity matrix is used to represent the identity transformation, 
which is a linear transformation that leaves all points unchanged. It is often used as a reference frame in the study of linear transformations, 
which are used to model many physical and biological phenomena.

Geometry: In geometry, the identity matrix is used to represent the identity transformation in Euclidean space, 
which is a translation that leaves all distances and angles unchanged. 
It is used to represent the concept of an "unchanged" object, such as a point or a vector.

Computer graphics: In computer graphics, the identity matrix is used to represent the identity transformation of an object in a 3D scene. 
It is used to position, orient, and scale objects in a scene.

Probability theory: In probability theory, the identity matrix is used to represent the identity function in the calculation of 
expectations, variances, and covariance matrices of random variables.
'''

np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
# Repeat an array
'''
The code creates a NumPy array arr with shape (1, 3) containing the values 1, 2, and 3, and then uses the np.repeat function to create a new array r1 by 
repeating arr three times along the first axis (rows).

The np.repeat function takes three arguments: the input array to be repeated, the number of repetitions, and the axis along which to repeat the array. 
In this case, the function call np.repeat(arr, 3, axis=0) repeats the array arr three times along the first axis (rows), resulting in an array with shape (3, 3).
'''

arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
